version: '3.3'
services:
  mysql: 
    image: mysql:5.7
    container_name: flavinus-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306

# Internal client
# docker exec -it flavinus-mysql mysql -uroot -p

# External client
# mysql -h 0.0.0.0 -P 3306 -u user -ppassword

# Import dump
# mysql db_name < backup-file.sql
